### ISSUE TITLE
Returns key not value on Android

### ISSUE THREAD

**Issue by jim1001** [trevordevore/levurehelper-translate#1]
All works as expected for me in the IDE. When I deploy to Android however I get the key of the translate item rather then the value. I've confirmed the build profile is correct so possibly the locale files aren't being copied correctly.

Looking at examples on 
https://github.com/trevordevore/levure/wiki/How-do-I-include-additional-files-and-folders-in-my-application-builds

the assets folder that sits alongside app.yml is included by `filename: assets`

However later a `folder_to_copy_1` that sits alongside app.yml is included by `filename: ./folder_to_copy_1`

Is the `./ `optional?

Anyhow I’ve tried both with same outcome.

Thanks,
Jim

**Comment by jim1001** [comment]
...I'll try it on the most basic of Levure projects & report back

**Comment by jim1001** [comment]
The simple project I created produced the correct results. I'll go back to the original project and see if I can figure out the problem with that.

**Comment by trevordevore** [comment]
@jim1001 `./` is optional. Although the README doesn't mention it, you will need to add `- filename: locales` somewhere in the `copy files` section. The `locales` folder probably isn't being copied over.

**Comment by jim1001** [comment]
Trevor,  Thanks for confirming the ./
In my simple trial it worked just by specifying `- filename: locales/en.yml`  & `- filename: locales/sv.yml`
Didn't need to specify `- filename: locales` as well.

**Comment by trevordevore** [comment]
That makes sense. If you specify `locales` then all files in the folder would be copied. If you are explicitly including files within the folder then you don't need to specify the folder.
